spring.datasource.url=jdbc:postgresql://localhost:5432/smart_traffic
spring.datasource.username=postgres
spring.datasource.password=otavioebia
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate cria as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra no console as tabelas sendo criadas
spring.jpa.show-sql=true